### ISSUE TITLE
module Urna is not loaded and could not be found

### ISSUE THREAD

**Issue by ararog** [meh/urna#5]
Hi,

No matter what I try I'm gettting the error described on title, I also tried to run the latest commented line on sample code from iex but the error still happens.

**Comment by meh** [comment]
How are you trying to run it?

**Comment by ararog** [comment]
I did the following steps:

* Created the project using mix new test --module Test
* Added urna as dependency on mix.exs
* Created a resources directory and inside it I placed a copy of test.ex with few changes like module name and removed :bar namespace

Started iex and insided it I typed:

c("resources/echo.ex"); Urna.start Test.Echo, port: 8080

**Comment by meh** [comment]
Did you start it with `iex -S mix`?

**Comment by ararog** [comment]
That did the trick, thanks!

**Comment by ararog** [comment]
By the way, it would be nice if we have some additions on README about compile and run the Urna powered apps, like place the ex file on lib folder, run mix compile to generate the project app and the command used to run the app.
